name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-26
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install swift-format and clang-format
        run: |
          brew install swift-format clang-format

      - name: Linting
        run: swift-format lint --recursive .
        continue-on-error: true

      - name: Formatting
        run: |
          swift-format format --recursive --in-place .
          clang-format -i nasalis/SMCBridge/SMCBridge.m nasalis/SMCBridge/include/SMCBridge.h
        continue-on-error: true

      - name: Get Swift version
        run: swift --version

      - name: Build Binary
        run: |
          swift build -c debug -Xswiftc -warn-concurrency
        continue-on-error: true

  package:
    runs-on: macos-26
    needs: build
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install create-dmg
        run: |
          brew install create-dmg

      - name: Build Binary
        run: |
          swift build -c release -Xswiftc -warn-concurrency

      - name: Create Bundle
        run: |
          mkdir -p "nasalis.app/Contents/MacOS"
          mkdir -p "nasalis.app/Contents/Resources"
          cp .build/release/nasalis "nasalis.app/Contents/MacOS/nasalis"
          cp -r nasalis/Resources/* "nasalis.app/Contents/Resources/"
          cp "nasalis/Supporting Files/Info.plist" "nasalis.app/Contents/Info.plist"

      - name: Create DMG
        run: |
          create-dmg --volname "nasalis" --skip-jenkins --no-internet-enable --filesystem APFS --icon "nasalis.app" 0 0 --hide-extension "nasalis.app" --app-drop-link 0 0 "nasalis.dmg" "nasalis.app"

      - name: Upload Binary
        uses: actions/upload-artifact@v6
        with:
          name: nasalis-binary
          path: .build/release/nasalis
          if-no-files-found: error

      - name: Upload Bundle
        uses: actions/upload-artifact@v6
        with:
          name: nasalis-app
          path: nasalis.app
          if-no-files-found: error

      - name: Upload DMG
        uses: actions/upload-artifact@v6
        with:
          name: nasalis-dmg
          path: nasalis.dmg
          if-no-files-found: error
